// <auto-generated />
namespace PassionProject_n01492913.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class wishlistsproducts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(wishlistsproducts));
        
        string IMigrationMetadata.Id
        {
            get { return "202202102351412_wishlists-products"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
